In [1]:
import pandas as pd
import os

In [2]:
dir_path = "C:\\Users\\Tejas\\Desktop\\Capstone\\DatasetsCleaned\\UniformClasses\\V2\\train"

In [3]:
file_names = []
for files in os.listdir(dir_path):
    file_names.append(files)

In [4]:
print(file_names)

['davidson_train.csv', 'hasoc_train.csv', 'hateval_train.csv', 'hatexplain_train.csv', 'ohc_train.csv', 'olid_train.csv', 'tcc_train.csv', 'trac_train.csv']

In [5]:
davidson = pd.read_csv(r'C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\UniformClasses\V2\train\davidson_train.csv', sep='\t')
hasoc = pd.read_csv(r'C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\UniformClasses\V2\train\hasoc_train.csv', sep='\t')

hateval = pd.read_csv(r'C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\UniformClasses\V2\train\hateval_train.csv', sep='\t')
hatexplain = pd.read_csv(r'C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\UniformClasses\V2\train\hatexplain_train.csv', sep='\t')
ohc = pd.read_csv(r'C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\UniformClasses\V2\train\ohc_train.csv', sep='\t')
olid = pd.read_csv(r'C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\UniformClasses\V2\train\olid_train.csv', sep='\t')
tcc = pd.read_csv(r'C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\UniformClasses\V2\train\tcc_train.csv', sep='\t')
trac = pd.read_csv(r'C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\UniformClasses\V2\train\davidson_train.csv', sep='\t')

In [7]:
## Combining Datasets

leave_davidson = pd.concat([hasoc, hateval, olid, trac, ohc, hatexplain, tcc])
leave_davidson

                                                    Text Class
0      small note sensibl peopl aroundðÿ'‡ðÿ»  under...   NOT
1                    decis respons bomb mbs murder liar    OFF
2      doctorsfightback new india agit fraud leader b...   OFF
3      â€œas prepar bright futur brexit itâ€™ vital r...   NOT
4      infact rate  star  like done good deed done zo...   NOT
...                                                  ...   ...
11995  "\n\nAgree. The example of the Garamond italic...   NOT
11996  Please see WP:BRD,   I'd much rather hammer ou...   NOT
11997  "\n\nIndeed, even her last name used for the a...   NOT
11998  i saw what you did and didn't realize the erro...   NOT
11999  yareli alvarado because she was the good and t...   NOT

[79486 rows x 2 columns]

In [8]:
leave_davidson.to_csv(r"C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\LeaveOneOut" + "\leave_davidson_train.csv", index=False)

In [9]:
leave_hasoc = pd.concat([davidson, hateval, olid, trac, ohc, hatexplain, tcc])
leave_hasoc

                                                    Text Class
0          rt justdoitrob kaaarlizzi bitch love laughlol   OFF
1                                 color everi day sunday   NOT
2                             ur brother look queer ugli   OFF
3                              sister bitch dont get way   OFF
4       pornandroidiphoneipadsexxxx  hairi  hairi pussi    OFF
...                                                  ...   ...
11995  "\n\nAgree. The example of the Garamond italic...   NOT
11996  Please see WP:BRD,   I'd much rather hammer ou...   NOT
11997  "\n\nIndeed, even her last name used for the a...   NOT
11998  i saw what you did and didn't realize the erro...   NOT
11999  yareli alvarado because she was the good and t...   NOT

[93704 rows x 2 columns]

In [10]:
leave_hasoc.to_csv(r"C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\LeaveOneOut" + "\leave_hasoc_train.csv", index=False)

In [11]:
leave_hateval = pd.concat([davidson, hasoc, olid, trac, ohc, hatexplain, tcc])
leave_hateval

                                                    Text Class
0          rt justdoitrob kaaarlizzi bitch love laughlol   OFF
1                                 color everi day sunday   NOT
2                             ur brother look queer ugli   OFF
3                              sister bitch dont get way   OFF
4       pornandroidiphoneipadsexxxx  hairi  hairi pussi    OFF
...                                                  ...   ...
11995  "\n\nAgree. The example of the Garamond italic...   NOT
11996  Please see WP:BRD,   I'd much rather hammer ou...   NOT
11997  "\n\nIndeed, even her last name used for the a...   NOT
11998  i saw what you did and didn't realize the erro...   NOT
11999  yareli alvarado because she was the good and t...   NOT

[90308 rows x 2 columns]

In [12]:
leave_hateval.to_csv(r"C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\LeaveOneOut" + "\leave_hateval_train.csv", index=False)

In [13]:
leave_olid = pd.concat([davidson, hasoc, hateval, trac, ohc, hatexplain, tcc])
leave_olid

                                                    Text Class
0          rt justdoitrob kaaarlizzi bitch love laughlol   OFF
1                                 color everi day sunday   NOT
2                             ur brother look queer ugli   OFF
3                              sister bitch dont get way   OFF
4       pornandroidiphoneipadsexxxx  hairi  hairi pussi    OFF
...                                                  ...   ...
11995  "\n\nAgree. The example of the Garamond italic...   NOT
11996  Please see WP:BRD,   I'd much rather hammer ou...   NOT
11997  "\n\nIndeed, even her last name used for the a...   NOT
11998  i saw what you did and didn't realize the erro...   NOT
11999  yareli alvarado because she was the good and t...   NOT

[86068 rows x 2 columns]

In [14]:
leave_olid.to_csv(r"C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\LeaveOneOut" + "\leave_olid_train.csv", index=False)

In [15]:
leave_trac = pd.concat([davidson, hasoc, hateval, olid, ohc, hatexplain, tcc])
leave_trac

                                                    Text Class
0          rt justdoitrob kaaarlizzi bitch love laughlol   OFF
1                                 color everi day sunday   NOT
2                             ur brother look queer ugli   OFF
3                              sister bitch dont get way   OFF
4       pornandroidiphoneipadsexxxx  hairi  hairi pussi    OFF
...                                                  ...   ...
11995  "\n\nAgree. The example of the Garamond italic...   NOT
11996  Please see WP:BRD,   I'd much rather hammer ou...   NOT
11997  "\n\nIndeed, even her last name used for the a...   NOT
11998  i saw what you did and didn't realize the erro...   NOT
11999  yareli alvarado because she was the good and t...   NOT

[79486 rows x 2 columns]

In [16]:
leave_trac.to_csv(r"C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\LeaveOneOut" + "\leave_trac_train.csv", index=False)

In [17]:
leave_ohc = pd.concat([davidson, hasoc, hateval, olid, trac, hatexplain, tcc])
leave_ohc

                                                    Text Class
0          rt justdoitrob kaaarlizzi bitch love laughlol   OFF
1                                 color everi day sunday   NOT
2                             ur brother look queer ugli   OFF
3                              sister bitch dont get way   OFF
4       pornandroidiphoneipadsexxxx  hairi  hairi pussi    OFF
...                                                  ...   ...
11995  "\n\nAgree. The example of the Garamond italic...   NOT
11996  Please see WP:BRD,   I'd much rather hammer ou...   NOT
11997  "\n\nIndeed, even her last name used for the a...   NOT
11998  i saw what you did and didn't realize the erro...   NOT
11999  yareli alvarado because she was the good and t...   NOT

[91023 rows x 2 columns]

In [18]:
leave_ohc.to_csv(r"C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\LeaveOneOut" + "\leave_ohc_train.csv", index=False)

In [19]:
leave_hatexplain = pd.concat([davidson, hasoc, hateval, olid, trac, ohc, tcc])
leave_hatexplain

                                                    Text Class
0          rt justdoitrob kaaarlizzi bitch love laughlol   OFF
1                                 color everi day sunday   NOT
2                             ur brother look queer ugli   OFF
3                              sister bitch dont get way   OFF
4       pornandroidiphoneipadsexxxx  hairi  hairi pussi    OFF
...                                                  ...   ...
11995  "\n\nAgree. The example of the Garamond italic...   NOT
11996  Please see WP:BRD,   I'd much rather hammer ou...   NOT
11997  "\n\nIndeed, even her last name used for the a...   NOT
11998  i saw what you did and didn't realize the erro...   NOT
11999  yareli alvarado because she was the good and t...   NOT

[87773 rows x 2 columns]

In [20]:
leave_hatexplain.to_csv(r"C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\LeaveOneOut" + "\leave_hatexplain_train.csv", index=False)

In [21]:
leave_tcc = pd.concat([davidson, hasoc, hateval, olid, trac, ohc, hatexplain])
leave_tcc

                                                    Text Class
0          rt justdoitrob kaaarlizzi bitch love laughlol   OFF
1                                 color everi day sunday   NOT
2                             ur brother look queer ugli   OFF
3                              sister bitch dont get way   OFF
4       pornandroidiphoneipadsexxxx  hairi  hairi pussi    OFF
...                                                  ...   ...
11530  so let me get this straight google youtube fac...   NOT
11531          just call her what she really is a nigger   OFF
11532  but imma have to get ghetto and start picking ...   OFF
11533  it muh dickism and biketheftism rolled into on...   OFF
11534  would some canadian patriot please maroon this...   OFF

[87308 rows x 2 columns]

In [22]:
leave_tcc.to_csv(r"C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\LeaveOneOut" + "\leave_tcc_train.csv", index=False)

In [23]:
leave_none = pd.concat([davidson, hasoc, hateval, olid, trac, ohc, hatexplain, tcc])

In [24]:
leave_none

                                                    Text Class
0          rt justdoitrob kaaarlizzi bitch love laughlol   OFF
1                                 color everi day sunday   NOT
2                             ur brother look queer ugli   OFF
3                              sister bitch dont get way   OFF
4       pornandroidiphoneipadsexxxx  hairi  hairi pussi    OFF
...                                                  ...   ...
11995  "\n\nAgree. The example of the Garamond italic...   NOT
11996  Please see WP:BRD,   I'd much rather hammer ou...   NOT
11997  "\n\nIndeed, even her last name used for the a...   NOT
11998  i saw what you did and didn't realize the erro...   NOT
11999  yareli alvarado because she was the good and t...   NOT

[99308 rows x 2 columns]

In [26]:
leave_none.to_csv(r"C:\Users\Tejas\Desktop\Capstone\DatasetsCleaned\LeaveOneOut" + "\combined_train.csv")

In [25]:
print(len(davidson) + len(leave_davidson))
print(len(hasoc) + len(leave_hasoc))
print(len(hateval) + len(leave_hateval))
print(len(olid) + len(leave_olid))
print(len(trac) + len(leave_trac))
print(len(ohc) + len(leave_ohc))
print(len(hatexplain) + len(leave_hatexplain))
print(len(tcc) + len(leave_tcc))

99308
99308
99308
99308
99308
99308
99308
99308